AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
